# Generated by Django 4.2.5 on 2023-10-11 06:54

import backend.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=30)),
                (
                    "username",
                    models.CharField(
                        max_length=30,
                        unique=True,
                        validators=[backend.validators.validate_username],
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        max_length=15, validators=[backend.validators.validate_password]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
