# Generated by Django 4.2.5 on 2023-10-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
